project:
  type: website

website:
  title: "🛖"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: chapters.qmd
        text: Chapters
      - href: activities.qmd
        text: Activities
      - href: updates.qmd
        text: Updates
      - href: contrib.qmd
        text: Contributors

format:
  html:
    theme:
      - cosmo
      - brand
    css: 
      - css/heliotrope.css
      - css/styles.css
      - css/tufte-extra.css
    toc: false
    page-layout: full
    title-block-banner: false
    title-block-style: none
    include-in-header:
      text: |
        <script src="js/chapter-links.js"></script>
